url: ldap://ipa.shared.example.opentlc.com or ldaps://ipa.shared.example.opentlc.com:636
bindDN: uid=admin,cn=users,cn=accounts,dc=shared,dc=example,dc=opentlc,dc=com 
bindPassword: r3dh4t1! 
insecure: false 
ca: /etc/origin/master/ipa-ca.crt 
